//
// Quagmire I - IV ciphers
//

#include "polyalphabetic.h"

/*
   Quagmire Ciphers: The General Case (Quagmire IV) and Specializations

   The Quagmire ciphers (I-IV) are a family of polyalphabetic substitution 
   ciphers that use a Vigenère-like sliding tableau generated from two or three
   keywords. The most general form is Quagmire IV.

   ## Quagmire IV: The General Cipher
   
   Quagmire IV is defined by three independent components, each generated by a 
   unique keyword:
   
   1.  **Plaintext Keyword (PT-KW):** Generates the substitution alphabet 
       for the *Plaintext* letters (the rows of the tableau). This is a 
       keyed alphabet (e.g., "CIPHER" followed by remaining letters A-Z).
   2.  **Ciphertext Keyword (CT-KW):** Generates the substitution alphabet 
       for the *Ciphertext* letters (the columns/sliding rule of the tableau). 
       This is also a keyed alphabet.
   3.  **Cycleword (CW):** Determines the shift/key selection for each position 
       in the message, just like in Vigenère. This is the indicator word.
   
   Encryption (E) and Decryption (D) involve finding the intersection between 
   the PT-KW row and the CT-KW/CW column, based on the Vigenère formula:
   
   $$E: C = (P + K) \pmod{26}$$
   $$D: P = (C - K) \pmod{26}$$
   
   Where P, C, and K are positions (0-25) in their respective keyword alphabets.

   ## Quagmire Specializations (I, II, III)

   Quagmire I, II, and III are simplified versions where one or more of the 
   keywords (PT-KW and CT-KW) are fixed to a simple **Straight Alphabet (A-Z)**, 
   equivalent to using a single-letter keyword.
      
   ### 1. Quagmire I
   
   **Specialization**: The Ciphertext Keyword (CT-KW) is fixed to a straight A-Z alphabet.
   
   * **Plaintext Keyword**: Scrambled (keyed by a word).
   * **Ciphertext Keyword**: Straight A-Z.
   * **Cycleword**: Scrambled (keyed by a word).
   
   ### 2. Quagmire II
   
   **Specialization**: The Plaintext Keyword (PT-KW) is fixed to a straight A-Z alphabet.
   
   * **Plaintext Keyword**: Straight A-Z.
   * **Ciphertext Keyword**: Scrambled (keyed by a word).
   * **Cycleword**: Scrambled (keyed by a word).
   
   ### 3. Quagmire III
   
   **Specialization**: Both the Plaintext Keyword (PT-KW) and Ciphertext Keyword (CT-KW) 
   are generated by the *same* scrambling keyword.
   
   * **Plaintext Keyword**: Scrambled (keyed by a word).
   * **Ciphertext Keyword**: *Identical* to PT-KW.
   * **Cycleword**: Scrambled (keyed by a word).
   
   **Note**: The Vigenère cipher (Type 0) is a further specialization where *both* the PT-KW and CT-KW are fixed to a straight A-Z alphabet.
*/

void quagmire_decrypt(int decrypted[], int cipher_indices[], int cipher_len,
    int plaintext_keyword_indices[], int ciphertext_keyword_indices[],
    int cycleword_indices[], int cycleword_len, bool variant) {

    int i, posn_keyword, posn_cycleword, indx;

    // Invert the ciphertext keyword once: ct_inverse[char] = its position in the
    // CT keyed alphabet. This replaces the two inner linear 26-scans (per char)
    // that previously dominated the decrypt, with O(1) lookups. This is the hot
    // path: quagmire_decrypt runs once per hill-climber iteration.
    int ct_inverse[ALPHABET_SIZE];
    for (i = 0; i < ALPHABET_SIZE; i++) ct_inverse[ciphertext_keyword_indices[i]] = i;

    // The cycleword char's position in the CT keyword depends only on the period
    // index (i % cycleword_len), so resolve all of them up front.
    int cw_pos[MAX_CYCLEWORD_LEN];
    for (i = 0; i < cycleword_len; i++) cw_pos[i] = ct_inverse[cycleword_indices[i]];

    for (i = 0; i < cipher_len; i++) {
        posn_keyword = ct_inverse[cipher_indices[i]];
        posn_cycleword = cw_pos[i % cycleword_len];

        if (variant) {
            indx = (posn_keyword + posn_cycleword)%ALPHABET_SIZE;
        } else {
            indx = (posn_keyword - posn_cycleword)%ALPHABET_SIZE;
        }

        if (indx < 0) indx += ALPHABET_SIZE;
        decrypted[i] = plaintext_keyword_indices[indx];
    }
}



void quagmire_encrypt(int encrypted[], int plaintext_indices[], int cipher_len,
    int plaintext_keyword_indices[], int ciphertext_keyword_indices[],
    int cycleword_indices[], int cycleword_len, bool variant) {

    int i, posn_keyword, posn_cycleword, indx;

    // Invert both keyed alphabets once (see quagmire_decrypt): the message char's
    // position comes from the PT keyword, the cycleword char's from the CT keyword.
    int pt_inverse[ALPHABET_SIZE], ct_inverse[ALPHABET_SIZE];
    for (i = 0; i < ALPHABET_SIZE; i++) {
        pt_inverse[plaintext_keyword_indices[i]] = i;
        ct_inverse[ciphertext_keyword_indices[i]] = i;
    }

    int cw_pos[MAX_CYCLEWORD_LEN];
    for (i = 0; i < cycleword_len; i++) cw_pos[i] = ct_inverse[cycleword_indices[i]];

    for (i = 0; i < cipher_len; i++) {
        posn_keyword = pt_inverse[plaintext_indices[i]];
        posn_cycleword = cw_pos[i % cycleword_len];

        if (variant) {
            indx = (posn_keyword - posn_cycleword)%ALPHABET_SIZE;
        } else {
            indx = (posn_keyword + posn_cycleword)%ALPHABET_SIZE;
        }
        if (indx < 0) indx += ALPHABET_SIZE;
        encrypted[i] = ciphertext_keyword_indices[indx];
    }
}
